import 'server-only'
import { serverEnv } from '@/lib/env'
import { canStoreSecrets } from '@/lib/crypto'

/**
 * CALENDAR PROVIDER ABSTRACTION
 * =============================================================================
 * Read-only, deliberately and structurally.
 *
 * There is no create, update, delete, accept or decline anywhere in this
 * interface. That is the safety property: V1 cannot modify someone's calendar
 * because the vocabulary to do so does not exist here, and adding it would be a
 * visible change to this file rather than a quiet change to a call site.
 *
 * Everything above this layer works in `NormalizedEvent`. Nothing in the domain
 * knows what Microsoft Graph or Google Calendar returns, which is what lets a
 * third provider be a new file rather than a migration.
 * =============================================================================
 */

export type CalendarProviderId = 'microsoft' | 'google'

export interface NormalizedAttendee {
  /** Lowercased. The only reliable join key onto a Person. */
  email: string | null
  /** Provider-supplied display name, used only when no Person matches. */
  displayName: string | null
  isOrganizer: boolean
  /** True for rooms, equipment and distribution lists — never a Person. */
  isResource: boolean
  /** 'accepted' | 'declined' | 'tentative' | 'none' */
  response: string
}

export interface NormalizedEvent {
  externalId: string
  calendarId: string | null
  title: string | null
  /** Omitted entirely for a private event. Never the full body. */
  description: string | null
  startsAt: string
  endsAt: string | null
  timeZone: string | null
  isAllDay: boolean
  location: string | null
  meetingUrl: string | null
  organizerEmail: string | null
  attendees: NormalizedAttendee[]
  /** Series identity. A moved occurrence keeps this and gets its own id. */
  recurrenceId: string | null
  isRecurring: boolean
  status: 'confirmed' | 'cancelled'
  isPrivate: boolean
  providerUpdatedAt: string | null
}

export type ProviderFailure =
  | 'not_configured'
  | 'unauthorized'
  | 'admin_consent_required'
  | 'rate_limited'
  | 'unavailable'
  | 'error'

export interface TokenSet {
  accessToken: string
  /** Absent when the provider does not re-issue one on refresh. */
  refreshToken?: string
  expiresAt: string
  scopes: string[]
  /** The account the grant belongs to, for display only. */
  accountEmail: string | null
}

export type ProviderResult<T> = { ok: true; value: T } | { ok: false; reason: ProviderFailure }

export interface ListEventsInput {
  accessToken: string
  from: Date
  to: Date
  calendarId?: string | null
  /** Provider change marker from the last sync, when there was one. */
  cursor?: string | null
}

export interface ListEventsOutput {
  events: NormalizedEvent[]
  /** Opaque. Stored and handed back next time; never parsed. */
  cursor: string | null
}

export interface CalendarProvider {
  readonly id: CalendarProviderId
  readonly label: string
  /** Whether this deployment has credentials for the provider at all. */
  readonly configured: boolean
  /** Exactly the scopes requested. Surfaced so the UI can be honest. */
  readonly scopes: string[]

  /** The URL to send the user to. State is generated by the caller. */
  authorizationUrl(input: { redirectUri: string; state: string }): string
  exchangeCode(input: { code: string; redirectUri: string }): Promise<ProviderResult<TokenSet>>
  refresh(input: { refreshToken: string }): Promise<ProviderResult<TokenSet>>
  listEvents(input: ListEventsInput): Promise<ProviderResult<ListEventsOutput>>
  /** Best-effort revocation at the provider. Disconnect never depends on it. */
  revoke(input: { refreshToken: string | null; accessToken: string }): Promise<void>
}

/**
 * Least privilege, stated once.
 *
 * Microsoft: Calendars.Read and nothing adjacent. `offline_access` is what
 * makes a refresh token possible, `openid`/`email` identify which account was
 * connected so the UI can show it. No Mail, no Contacts, no Files, and
 * emphatically no ReadWrite.
 */
export const MICROSOFT_SCOPES = [
  'offline_access',
  'openid',
  'email',
  'https://graph.microsoft.com/Calendars.Read',
]

/**
 * Google: the events-only read scope, which is narrower than calendar.readonly
 * — it grants events without granting the calendar list and settings.
 */
export const GOOGLE_SCOPES = [
  'openid',
  'email',
  'https://www.googleapis.com/auth/calendar.events.readonly',
]

/** Recognisable conference links, so Prepare can offer to join. */
export function extractMeetingUrl(...candidates: (string | null | undefined)[]): string | null {
  const pattern =
    /https:\/\/(?:[a-z0-9-]+\.)?(?:teams\.microsoft\.com|meet\.google\.com|zoom\.us|whereby\.com|meet\.jit\.si)\/[^\s"'<>)]+/i

  for (const candidate of candidates) {
    const match = candidate?.match(pattern)
    if (match) return match[0]
  }
  return null
}

/**
 * Whether an attendee is a person rather than a room, a piece of equipment or a
 * distribution list. Matching a Person record to "Meeting Room 3" would put a
 * conference room in someone's relationship graph.
 */
export function looksLikeResource(input: {
  email: string | null
  displayName: string | null
  providerType?: string | null
}): boolean {
  if (input.providerType === 'resource' || input.providerType === 'room') return true

  const haystack = `${input.email ?? ''} ${input.displayName ?? ''}`.toLowerCase()
  return /\b(room|rm\d|boardroom|meeting-?room|conf(erence)?-?room|projector|equipment|resource|no-?reply|noreply|calendar@|rooms?@)\b/.test(
    haystack,
  )
}

/**
 * Configured means connecting would actually work.
 *
 * The encryption key is tested with canStoreSecrets rather than for presence:
 * a key shorter than 32 characters is refused by lib/crypto, so treating a
 * short one as configured would offer a Connect button that sends someone
 * through a provider consent screen and then refuses to store the grant. The
 * two checks have to agree, and this is the side that must not be the more
 * generous of the pair.
 */
export function providerConfigured(id: CalendarProviderId): boolean {
  if (id === 'microsoft') {
    return Boolean(
      serverEnv.MICROSOFT_CLIENT_ID && serverEnv.MICROSOFT_CLIENT_SECRET && canStoreSecrets(),
    )
  }
  return Boolean(serverEnv.GOOGLE_CLIENT_ID && serverEnv.GOOGLE_CLIENT_SECRET && canStoreSecrets())
}

/** Whether the encryption key is absent, present but unusable, or fine. */
export function tokenKeyState(): 'ok' | 'missing' | 'too_short' {
  if (canStoreSecrets()) return 'ok'
  return serverEnv.TOKEN_ENCRYPTION_KEY ? 'too_short' : 'missing'
}

/**
 * Which of the variables this provider needs are absent at runtime.
 *
 * Names only, never values, and only ever the names of variables that are
 * unset -- which discloses nothing a reader could not already infer from the
 * feature being off.
 *
 * It exists because the alternative misleads. Listing all three whenever the
 * calendar is unavailable sends an operator who has already set two of them
 * back to re-check settings that were never the problem, and gives no way to
 * tell "I have not configured this yet" apart from "I configured it and the
 * deployment cannot see one of them" -- which are different problems with
 * different fixes.
 */
export function missingProviderEnv(id: CalendarProviderId): string[] {
  const required: [name: string, value: string | undefined][] =
    id === 'microsoft'
      ? [
          ['MICROSOFT_CLIENT_ID', serverEnv.MICROSOFT_CLIENT_ID],
          ['MICROSOFT_CLIENT_SECRET', serverEnv.MICROSOFT_CLIENT_SECRET],
          ['TOKEN_ENCRYPTION_KEY', canStoreSecrets() ? 'set' : undefined],
        ]
      : [
          ['GOOGLE_CLIENT_ID', serverEnv.GOOGLE_CLIENT_ID],
          ['GOOGLE_CLIENT_SECRET', serverEnv.GOOGLE_CLIENT_SECRET],
          ['TOKEN_ENCRYPTION_KEY', canStoreSecrets() ? 'set' : undefined],
        ]

  return required.filter(([, value]) => !value).map(([name]) => name)
}
